# Generated by Django 5.0.4 on 2026-06-01 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.PositiveIntegerField()),
                ('table_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('awaiting_payment', 'Ожидает оплату'), ('payment_requested', 'Запрошена оплата'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge_percent', models.PositiveIntegerField(default=10)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tables.table')),
            ],
            options={
                'db_table': 'table_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('waiter_confirmed', 'Принят официантом'), ('sent_to_kitchen', 'Отправлен на кухню'), ('sent_to_bar', 'Отправлен в бар'), ('ready', 'Готово'), ('served', 'Подано'), ('delivered', 'Доставлено'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('preparation_station', models.CharField(default='kitchen', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('added_by', models.CharField(choices=[('guest', 'Гость'), ('waiter', 'Официант')], default='guest', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_sessions.tablesession')),
            ],
            options={
                'db_table': 'session_items',
            },
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'status'], name='table_sessi_restaur_97b317_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['table_token', 'status'], name='table_sessi_table_t_aaeceb_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'closed_at'], name='table_sessi_restaur_88d4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['session', 'status'], name='session_ite_session_38dc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['session', 'preparation_station'], name='session_ite_session_40797d_idx'),
        ),
    ]
