# Generated by Django 5.0.4 on 2026-06-01 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_charge_percent', models.PositiveIntegerField(default=10)),
                ('allow_waiter_close', models.BooleanField(default=False)),
                ('kaspi_pay_url', models.URLField(blank=True)),
                ('panorama_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('iiko_enabled', models.BooleanField(default=False)),
                ('iiko_url', models.CharField(blank=True, max_length=255)),
                ('iiko_login', models.CharField(blank=True, max_length=255)),
                ('iiko_password', models.CharField(blank=True, max_length=255)),
                ('iiko_org_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurants',
                'indexes': [models.Index(fields=['slug'], name='restaurants_slug_0c26aa_idx'), models.Index(fields=['is_public'], name='restaurants_is_publ_ef5343_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'promos',
                'indexes': [models.Index(fields=['restaurant', 'is_active'], name='promos_restaur_eab9ab_idx')],
            },
        ),
    ]
