import { useEffect, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { api, type DjangoMenuItem, type UpsellRule } from '../../lib/api'

export default function UpsellRulesPanel({ restId, items, onToast }: { restId: string; items: DjangoMenuItem[]; onToast: (s:string)=>void }) {
  const [rules,setRules]=useState<UpsellRule[]>([]), [trigger,setTrigger]=useState(''), [target,setTarget]=useState(''), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false)
  const load=async()=>{ setLoading(true); try{setRules(await api.upsellRules(restId))}catch{onToast('Не удалось загрузить upsell-правила')}finally{setLoading(false)} }
  useEffect(()=>{load()},[restId])
  const add=async()=>{ if(!trigger||!target||trigger===target)return; setSaving(true); try{const r=await api.createUpsellRule(restId,{trigger_item:trigger,recommended_item:target});setRules(v=>[...v,r]);setTrigger('');setTarget('');onToast('Upsell-правило добавлено')}catch(e:any){onToast(e?.data?.non_field_errors?.[0]??'Не удалось добавить правило')}finally{setSaving(false)} }
  const remove=async(id:string)=>{try{await api.deleteUpsellRule(restId,id);setRules(v=>v.filter(r=>r.id!==id));onToast('Правило удалено')}catch{onToast('Не удалось удалить правило')}}
  return <div className="adm-card p-4 flex flex-col gap-3"><div><p className="font-bold text-sm" style={{color:'var(--color-soft)'}}>Умные допродажи без AI</p><p className="text-xs" style={{color:'var(--color-mid)'}}>Если гость добавил блюдо → покажем выбранное дополнение в корзине.</p></div>
    <div className="grid grid-cols-1 sm:grid-cols-[1fr_1fr_auto] gap-2"><select value={trigger} onChange={e=>setTrigger(e.target.value)} className="px-3 py-2.5 rounded-xl text-sm" style={{background:'var(--color-card)',border:'1px solid var(--color-rim)',color:'var(--color-soft)'}}><option value="">Если в корзине…</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><select value={target} onChange={e=>setTarget(e.target.value)} className="px-3 py-2.5 rounded-xl text-sm" style={{background:'var(--color-card)',border:'1px solid var(--color-rim)',color:'var(--color-soft)'}}><option value="">Предложить…</option>{items.filter(i=>i.id!==trigger).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><button disabled={saving||!trigger||!target} onClick={add} className="px-4 py-2.5 rounded-xl font-bold text-sm disabled:opacity-50" style={{background:'var(--color-gold)',color:'#fff'}}><Plus size={15} className="inline"/> Добавить</button></div>
    {loading?<p className="text-xs" style={{color:'var(--color-mid)'}}>Загрузка правил…</p>:rules.length===0?<p className="text-xs" style={{color:'var(--color-mid)'}}>Правил пока нет. Например: бургер → напиток.</p>:<div className="flex flex-col gap-2">{rules.map(r=><div key={r.id} className="flex items-center gap-2 px-3 py-2 rounded-xl" style={{background:'var(--color-card2)'}}><span className="text-xs flex-1" style={{color:'var(--color-soft)'}}>{r.trigger_item_name} → <b>{r.recommended_item_name}</b></span><button onClick={()=>remove(r.id)} aria-label="Удалить правило"><Trash2 size={15} style={{color:'var(--color-mid)'}}/></button></div>)}</div>}
  </div>
}
