# Generated by Django 5.0.4 on 2026-06-01 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, choices=[('hit', 'Хит'), ('new', 'Новинка'), ('sale', 'Скидка')], max_length=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('preparation_station', models.CharField(choices=[('kitchen', 'Кухня'), ('bar', 'Бар')], default='kitchen', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('iiko_product_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'sort_order'], name='categories_restaur_511dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available', 'is_visible'], name='menu_items_restaur_608b90_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category'], name='menu_items_categor_de3aed_idx'),
        ),
    ]
