import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, RefreshCw, Siren, Receipt, Bell, UserCheck } from 'lucide-react'
import { api, type OperationsException, type OperationsExceptionsResponse } from '../../lib/api'
import { useAdminStore } from '../store'

type Filter = 'all' | OperationsException['kind']
export default function ExceptionsTab() {
  const { djangoRestId, setTab, setSessionDetail } = useAdminStore()
  const [data,setData]=useState<OperationsExceptionsResponse|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState(''), [filter,setFilter]=useState<Filter>('all'), [busy,setBusy]=useState('')
  const load=useCallback(async(silent=false)=>{if(!djangoRestId)return;if(!silent)setLoading(true);try{setData(await api.operationsExceptions(djangoRestId));setError('')}catch{setError('Не удалось загрузить очередь проблем.')}finally{if(!silent)setLoading(false)}},[djangoRestId])
  useEffect(()=>{load();const id=setInterval(()=>load(true),8000);return()=>clearInterval(id)},[load])
  const rows=useMemo(()=>data?.exceptions.filter(x=>filter==='all'||x.kind===filter)??[],[data,filter])
  const go=(x:OperationsException)=>{if(x.action==='session'&&x.session_id){setTab('sessions');setSessionDetail(x.session_id)}else if(x.action==='calls')setTab('calls')}
  const own=async(x:OperationsException)=>{if(!djangoRestId)return;setBusy(x.id);try{await api.acknowledgeOperationException(djangoRestId,x.id,x.acknowledged_at?'unassign':'acknowledge');await load(true)}catch{setError('Не удалось изменить ответственного. Обновите очередь и повторите.')}finally{setBusy('')}}
  if(loading&&!data)return <div className="p-5 text-sm" style={{color:'var(--color-mid)'}}>Загрузка операционной очереди…</div>
  return <div className="space-y-4 pb-24"><div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-extrabold" style={{color:'var(--color-soft)'}}>Проблемы</h1><p className="text-xs mt-1" style={{color:'var(--color-dim)'}}>Срочное → ответственный → решение · обновление каждые 8 сек</p></div><button aria-label="Обновить" onClick={()=>load()} className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:'var(--color-card2)',border:'1px solid var(--color-rim)'}}><RefreshCw size={16}/></button></div>
  {error&&<div className="rounded-2xl p-4 flex items-center justify-between gap-3" style={{background:'rgba(239,68,68,.08)',border:'1px solid rgba(239,68,68,.25)'}}><span className="text-sm">{error}</span><button onClick={()=>load()} className="font-bold text-sm">Повторить</button></div>}
  {data&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{[['Всего',data.counts.total],['Критично',data.counts.critical],['Внимание',data.counts.warning],['В работе',data.counts.acknowledged]].map(([k,v])=><div key={String(k)} className="rounded-2xl p-3" style={{background:'var(--color-card)',border:'1px solid var(--color-rim)'}}><div className="text-xl font-extrabold">{v}</div><div className="text-[11px]" style={{color:'var(--color-dim)'}}>{k}</div></div>)}</div>}
  <div className="flex gap-2 overflow-x-auto pb-1">{([['all','Все'],['sla','SLA'],['call','Вызовы'],['payment','Оплата'],['order','Заказы']] as const).map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className="px-3 py-2 rounded-xl text-xs font-bold whitespace-nowrap" style={{background:filter===id?'rgba(255,107,26,.14)':'var(--color-card2)',color:filter===id?'var(--color-gold)':'var(--color-mid)'}}>{label}</button>)}</div>
  {!rows.length&&!error?<div className="rounded-3xl p-8 text-center" style={{background:'var(--color-card)',border:'1px solid var(--color-rim)'}}><Siren size={30} className="mx-auto mb-3"/><div className="font-bold">Активных проблем нет</div><div className="text-xs mt-1" style={{color:'var(--color-dim)'}}>Операционная очередь чистая.</div></div>:<div className="space-y-2">{rows.map(x=><div key={x.id} className="rounded-2xl p-4" style={{background:'var(--color-card)',border:`1px solid ${x.severity==='critical'?'rgba(239,68,68,.35)':'rgba(245,158,11,.3)'}`}}><button onClick={()=>go(x)} className="w-full text-left flex gap-3 items-start"><span>{x.kind==='call'?<Bell size={18}/>:x.kind==='payment'?<Receipt size={18}/>:<AlertTriangle size={18}/>}</span><div className="min-w-0 flex-1"><div className="font-bold text-sm">{x.title}</div><div className="text-xs mt-1" style={{color:'var(--color-mid)'}}>{x.detail}</div>{x.acknowledged_by&&<div className="text-[11px] mt-2 flex items-center gap-1" style={{color:'var(--color-gold)'}}><UserCheck size={12}/>В работе: {x.acknowledged_by.name}{x.response_minutes!=null?` · реакция ${x.response_minutes} мин`:''}</div>}</div><span className="text-[10px] font-extrabold uppercase" style={{color:x.severity==='critical'?'var(--color-red)':'var(--color-gold)'}}>{x.severity==='critical'?'Срочно':'Внимание'}</span></button><button disabled={busy===x.id} onClick={()=>own(x)} className="mt-3 w-full min-h-10 rounded-xl text-xs font-bold" style={{background:'var(--color-card2)',border:'1px solid var(--color-rim)'}}>{busy===x.id?'Сохраняем…':x.acknowledged_at?'Снять ответственного':'Взять в работу'}</button></div>)}</div>}</div>
}
