import React, { useEffect, useState } from 'react'
import { Plus, RefreshCw, Send, Trash2 } from 'lucide-react'
import { api, type NetworkMenuTemplateItem } from '../../lib/api'

export default function NetworkMenuPanel({ networkId }: { networkId: string }) {
  const [items,setItems]=useState<NetworkMenuTemplateItem[]>([]), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [error,setError]=useState('')
  const [name,setName]=useState(''), [category,setCategory]=useState(''), [price,setPrice]=useState('')
  const load=()=>{setLoading(true);setError('');api.networkMenuTemplate(networkId).then(setItems).catch(e=>setError(String(e?.message??e))).finally(()=>setLoading(false))}
  useEffect(load,[networkId])
  const add=async()=>{if(!name.trim()||!price||busy)return;setBusy(true);setError('');try{await api.createNetworkMenuTemplateItem(networkId,{name:name.trim(),category_name:category.trim(),price,preparation_station:'kitchen',is_available:true,is_visible:true,sort_order:items.length});setName('');setCategory('');setPrice('');load()}catch(e:any){setError(String(e?.message??e))}finally{setBusy(false)}}
  const publish=async()=>{setBusy(true);setError('');try{const r=await api.publishNetworkMenu(networkId);alert(`Меню опубликовано: ${r.branches} филиал(а), создано ${r.created}, обновлено ${r.updated}`)}catch(e:any){setError(String(e?.message??e))}finally{setBusy(false)}}
  if(loading)return <div className="adm-card p-6 mt-5 text-center"><RefreshCw className="animate-spin mx-auto"/><p className="text-sm mt-2">Загружаем центральное меню…</p></div>
  return <div className="adm-card p-4 sm:p-5 mt-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="font-bold">Центральное меню сети</h2><p className="text-xs mt-1" style={{color:'var(--color-mid)'}}>Один шаблон → все проверенные филиалы. Локальные overrides цены/наличия сохраняются.</p></div><button disabled={busy||!items.length} onClick={publish} className="adm-btn flex items-center justify-center gap-2"><Send size={15}/>{busy?'Публикуем…':'Опубликовать во все филиалы'}</button></div>{error&&<p className="text-sm mt-3" style={{color:'var(--color-red)'}}>{error}</p>}<div className="grid grid-cols-1 sm:grid-cols-3 gap-2 mt-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Блюдо" className="px-3 py-2.5 rounded-xl" style={{background:'var(--color-card2)',border:'1px solid var(--color-rim)'}}/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Категория" className="px-3 py-2.5 rounded-xl" style={{background:'var(--color-card2)',border:'1px solid var(--color-rim)'}}/><div className="flex gap-2"><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Цена ₸" className="min-w-0 flex-1 px-3 py-2.5 rounded-xl" style={{background:'var(--color-card2)',border:'1px solid var(--color-rim)'}}/><button onClick={add} disabled={busy||!name.trim()||!price} className="adm-btn"><Plus size={16}/></button></div></div>{items.length===0?<p className="text-sm py-6 text-center" style={{color:'var(--color-mid)'}}>Шаблон пуст. Добавьте первое блюдо.</p>:<div className="mt-4 divide-y" style={{borderColor:'var(--color-rim)'}}>{items.map(i=><div key={i.id} className="py-3 flex items-center gap-3"><div className="min-w-0 flex-1"><p className="font-semibold truncate">{i.name}</p><p className="text-xs" style={{color:'var(--color-mid)'}}>{i.category_name||'Без категории'} · {Number(i.price).toLocaleString('ru')} ₸</p></div><button disabled={busy} onClick={async()=>{if(!confirm(`Удалить «${i.name}» из шаблона?`))return;setBusy(true);try{await api.deleteNetworkMenuTemplateItem(networkId,i.id);load()}finally{setBusy(false)}}} className="p-2 rounded-lg" style={{color:'var(--color-red)'}}><Trash2 size={15}/></button></div>)}</div>}</div>
}
