# Generated by Django 5.0.4 on 2026-06-01 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.PositiveIntegerField()),
                ('table_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('closed', 'Закрыт')], default='new', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
            ],
            options={
                'db_table': 'waiter_calls',
                'indexes': [models.Index(fields=['restaurant', 'status'], name='waiter_call_restaur_4f2cb5_idx')],
            },
        ),
    ]
